name: Build & Release FOSS APK with Metadataon:
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build FOSS APK
        run: ./gradlew :app:assembleProdFossWebsiteRelease

      - name: Find APK and Extract Version/Package Info
        id: apk_info
        run: |
          APK_PATH=$(find app/build/outputs/apk/prodFossWebsite/release/ -name "*.apk" | head -n 1)
          MANIFEST="app/build/intermediates/merged_manifests/prodFossWebsiteRelease/AndroidManifest.xml"
          
          # Estrae i valori dall'AndroidManifest.xml generato dalla build
          VERSION_NAME=$(grep "android:versionName=" $MANIFEST | sed 's/.*versionName="//;s/".*//')
          VERSION_CODE=$(grep "android:versionCode=" $MANIFEST | sed 's/.*versionCode="//;s/".*//')
          PACKAGE_NAME=$(grep "package=" $MANIFEST | sed 's/.*package="//;s/".*//')

          # Imposta gli output per gli step successivi
          echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT
          echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT
          echo "version_code=$VERSION_CODE" >> $GITHUB_OUTPUT
          echo "package_name=$PACKAGE_NAME" >> $GITHUB_OUTPUT
          echo "release_tag=v$VERSION_NAME" >> $GITHUB_OUTPUT
          
          echo "Found APK at $APK_PATH"
          echo "Version Name: $VERSION_NAME"
          echo "Version Code: $VERSION_CODE"
          echo "Package Name: $PACKAGE_NAME"

      - name: Compute SHA256 of APK
        id: apkhash
        run: |
          HASH=$(sha256sum "${{ steps.apk_info.outputs.apk_path }}" | awk '{print $1}')
          echo "apk_hash=$HASH" >> $GITHUB_OUTPUT

      - name: Generate JSON Metadata
        run: |
          APK_FILENAME=$(basename "${{ steps.apk_info.outputs.apk_path }}")
          cat <<EOF > index-v1.json
          {
            "packages": {
              "${{ steps.apk_info.outputs.package_name }}": [
                {
                  "versionName": "${{ steps.apk_info.outputs.version_name }}",
                  "versionCode": ${{ steps.apk_info.outputs.version_code }},
                  "apkName": "$APK_FILENAME",
                  "apkSha256": "${{ steps.apkhash.outputs.apk_hash }}"
                }
              ]
            }
          }
          EOF

      - name: Create GitHub Release with APK and Metadata
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.apk_info.outputs.release_tag }}
          name: Release ${{ steps.apk_info.outputs.version_name }}
          files: |
            ${{ steps.apk_info.outputs.apk_path }}
            index-v1.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
